variables:
    VAGRANT_DEFAULT_PROVIDER: lxc
before_script:
    - mkdir -p ../${PWD##*/}.vagrant
    - ln -s ../${PWD##*/}.vagrant .vagrant
    - git submodule sync
    - git submodule update --init

build:
    script: "./gitlabci-runner.sh"
    tags:
        - shell
        - lxc
## .deb artifact too big for GitLab CI
#    artifacts:
#      paths:
#        - ./*.deb
