variables:
    VAGRANT_DEFAULT_PROVIDER: lxc
before_script:
    - mkdir -p ../${PWD##*/}.vagrant
    - ln -s ../${PWD##*/}.vagrant .vagrant
    - debian/rules get-orig-source
build:
    script:
        - dpkg-buildpackage -b
    tags:
        - shell
        - lxc
