---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    ## Install some base packages and configuration files, this should be ok for all projects
    - { role: base }
    - { role: git }

  tasks:
    - name: Enable jessie-backports repository
      apt_repository: repo='deb http://deb.debian.org/debian/ jessie-backports main' state=present update_cache=yes
      become: yes
    - name: Install build-dependencies from backports when needed
      apt: pkg={{ item }} default_release=jessie-backports state=latest
      become: yes
      with_items:
        - dpkg-dev
        - debhelper
        - dh-systemd
        - devscripts
        - quilt
